#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folder

mkdir -p /config/qBittorrent

configFilePath="/config/qBittorrent/qBittorrent.conf"

declare -A configMap

# copy default config
if [[ ! -f $configFilePath ]]; then
    cp /defaults/qBittorrent.conf "$configFilePath"
fi

python3 /config_setup.py "$configFilePath"

# chown download directory if currently not set to abc
if grep -qe ' /downloads ' /proc/mounts; then
    lsiown abc:abc /downloads
fi

# permissions
lsiown -R abc:abc \
    /config
